"""Initial schema, row-level security, and the append-only audit log.

Revision ID: 0001
Revises:
Create Date: 2026-09-14

## Why this revision builds tables from metadata

The table DDL here comes from ``Base.metadata.create_all`` rather than an
explicit list of ``op.create_table`` calls. That is a deliberate choice for the
BOOTSTRAP revision only, and it is the one place it is defensible: there is no
deployed database to diff against yet, so a hand-transcribed 25-table DDL block
would be a large surface for typos with nothing to catch them.

**Every subsequent revision must be a real autogenerated diff.** Once this has
been applied once, run::

    alembic revision --autogenerate -m "describe the change"

and commit the explicit operations. Do not add more ``create_all`` revisions —
a migration that changes meaning when the models change is not a migration.

## Row-level security

RLS is layer 3 of the three described in ``suliko.db.tenancy``. It catches raw
SQL and anything that bypasses the ORM filter. The policy reads
``current_setting('suliko.tenant_id')``, which ``session_scope`` sets
transaction-locally on each connection.

Note the ``NULLIF(..., '')`` and the ``true`` second argument to
``current_setting``: without them, a connection that never set the GUC raises
rather than returning no rows, which turns a missing tenant into a 500 on every
endpoint instead of an empty result.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from suliko.models import Base

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

#: The application connects as this role. It is deliberately NOT the owner of
#: the tables: a table owner bypasses RLS unless FORCE is set, and relying on
#: FORCE alone means one missed FORCE is a silent cross-tenant leak.
APP_ROLE = "suliko_app"

# Role and table names are interpolated into DDL below. That is unavoidable —
# PostgreSQL does not accept bind parameters for identifiers — so both sources
# are constrained instead: APP_ROLE is a literal in this file, and the table
# names come from SQLAlchemy metadata, never from user input. Ruff's S608 is
# suppressed per-statement rather than file-wide so a future f-string carrying
# real user data still trips it.


#: Tables that belong to LATER revisions and must not be built here.
#:
#: ``create_all`` builds whatever is in ``Base.metadata`` *at the moment the
#: migration runs*, which is the current models package — not the models as
#: they stood when this revision was written. Without this exclusion, 0001
#: creates the collaboration and CMS tables and 0002 then fails trying to
#: create them again, so ``alembic upgrade head`` never completes on a fresh
#: database.
#:
#: Kept in sync with 0002's ``NEW_TABLES`` by ``tests/test_migration_parity.py``.
#: Every future revision that adds a table must add it here too — or, better,
#: stop this revision from being the only one built from metadata.
LATER_REVISION_TABLES = frozenset(
    {
        "order_comments",
        "order_comment_mentions",
        "order_comment_reads",
        "notifications",
        "service_pages",
        "site_strings",
        # 0003
        "integration_credentials",
    }
)


def _revision_tables() -> list[sa.Table]:
    """The tables this revision owns, in dependency order."""
    return [
        table
        for table in Base.metadata.sorted_tables
        if table.name not in LATER_REVISION_TABLES
    ]


def _tenant_scoped_tables() -> list[str]:
    """Tables carrying a ``tenant_id``, in dependency order.

    Scoped to this revision's own tables: applying RLS to a table 0002 has not
    created yet would fail, and 0002 applies its own.
    """
    return [
        table.name
        for table in _revision_tables()
        if "tenant_id" in table.columns and table.name != "audit_log"
    ]


def upgrade() -> None:
    bind = op.get_bind()

    # ── Tables ──────────────────────────────────────────────────────────────
    # Only this revision's own tables — see LATER_REVISION_TABLES.
    Base.metadata.create_all(bind, tables=_revision_tables())

    # ── Application role ────────────────────────────────────────────────────
    # Created without a password: it is granted to the connecting user rather
    # than logged into directly. Adjust to your deployment's auth model.
    op.execute(
        sa.text(
            f"""
            DO $$
            BEGIN
                IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '{APP_ROLE}') THEN
                    CREATE ROLE {APP_ROLE} NOLOGIN;
                END IF;
            END
            $$;
            """
        )
    )
    op.execute(sa.text(f"GRANT USAGE ON SCHEMA public TO {APP_ROLE}"))
    op.execute(
        sa.text(
            f"GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO {APP_ROLE}"
        )
    )
    op.execute(sa.text(f"GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO {APP_ROLE}"))

    # ── Row-level security on every tenant-scoped table ─────────────────────
    for table in _tenant_scoped_tables():
        op.execute(sa.text(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY"))
        # FORCE so that even the table owner is subject to the policy. Without
        # it, running the app as the owner silently disables isolation.
        op.execute(sa.text(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY"))
        op.execute(
            sa.text(
                f"""
                CREATE POLICY tenant_isolation ON {table}
                USING (
                    tenant_id = NULLIF(current_setting('suliko.tenant_id', true), '')::bigint
                )
                WITH CHECK (
                    tenant_id = NULLIF(current_setting('suliko.tenant_id', true), '')::bigint
                );
                """
            )
        )

    # ── Audit log: append-only ──────────────────────────────────────────────
    # The application can INSERT and SELECT but never UPDATE or DELETE. An
    # audit log the application can rewrite is not evidence of anything.
    op.execute(sa.text(f"REVOKE UPDATE, DELETE ON audit_log FROM {APP_ROLE}"))
    op.execute(
        sa.text(
            """
            CREATE OR REPLACE FUNCTION audit_log_is_append_only()
            RETURNS TRIGGER AS $$
            BEGIN
                RAISE EXCEPTION 'audit_log is append-only: % is not permitted', TG_OP;
            END;
            $$ LANGUAGE plpgsql;
            """
        )
    )
    op.execute(
        sa.text(
            """
            CREATE TRIGGER audit_log_no_mutation
            BEFORE UPDATE OR DELETE ON audit_log
            FOR EACH ROW EXECUTE FUNCTION audit_log_is_append_only();
            """
        )
    )

    # ── Case-insensitive search support ─────────────────────────────────────
    # Client/translator/notary lists search with ILIKE '%term%', which no btree
    # index can serve. pg_trgm makes those indexable. Created here so the index
    # can simply be added when list volume justifies it.
    op.execute(sa.text("CREATE EXTENSION IF NOT EXISTS pg_trgm"))
    op.execute(
        sa.text("CREATE INDEX ix_clients_name_trgm ON clients USING gin (name gin_trgm_ops)")
    )


def downgrade() -> None:
    op.execute(sa.text("DROP INDEX IF EXISTS ix_clients_name_trgm"))
    op.execute(sa.text("DROP TRIGGER IF EXISTS audit_log_no_mutation ON audit_log"))
    op.execute(sa.text("DROP FUNCTION IF EXISTS audit_log_is_append_only()"))

    for table in _tenant_scoped_tables():
        op.execute(sa.text(f"DROP POLICY IF EXISTS tenant_isolation ON {table}"))
        op.execute(sa.text(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY"))

    Base.metadata.drop_all(op.get_bind(), tables=_revision_tables())
    # The role is left in place: it may own objects outside this database.
